### ISSUE TITLE
Ajout d'un nouveau site pour la GA Paques

### ISSUE THREAD

**Issue by bmagic** [Futurolan/ga-front#1]
J'aimerai avoir si c'est possible : 
- Le nom de la lan exact 
- Le port sur lequel le reverse proxy pointe 
- L'url finale du front

**Comment by mupfpilou** [comment]
- Gamers Assembly Festival Edition
- 3006
- festival2019.gamers-assembly.net

**Comment by mupfpilou** [comment]
ga2019.gamers-assembly.net en fait

**Comment by bmagic** [comment]
Done reste plus qu'à binder le reverse proxy.
Je te laisse fermer le ticket ensuite @mupfpilou

**Comment by mupfpilou** [comment]
done
