### ISSUE TITLE
Affichage des slots réservés

### ISSUE THREAD

**Issue by mupfpilou** [Futurolan/ga-front#11]
sur la v1, on avait mis des cadenas avec un txt "Slot réservé"
A conserver sur la v2

**Comment by bmagic** [comment]
C'est déjà en place, ils ne s'affiche que lorsque tu auras activé au moins une fois le fetch de weezevent dans la node édition. 

Je peux fixe ça mais bon de toute façon quand tu ouvres des tournois tu as normalement configuré le fetch de weezevent non ?
