### ISSUE TITLE
Le module de scheduling a planté le site, a priori

### ISSUE THREAD

**Issue by mupfpilou** [Futurolan/ga-front#7]
Ce matin : 
- sites sans lien billetterie
- unknown error en bas de chaque page du backend
- dans les logs du container, cette erreur : 

[Sat Oct 27 08:42:51.656360 2018] [php7:notice] [pid 204] [client 172.18.0.6:48712] Error: Call to a member function getPlugin() on null in /var/www/drupal/web/modules/contrib/scheduler/src/SchedulerManager.php on line 196 #0 /var/www/drupal/web/modules/contrib/scheduler/scheduler.module(426): Drupal\\scheduler\\SchedulerManager->publish()\n#1 [internal function]: scheduler_cron()\n#2 /var/www/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(392): call_user_func_array('scheduler_cron', Array)\n#3 /var/www/drupal/web/core/lib/Drupal/Core/Cron.php(235): Drupal\\Core\\Extension\\ModuleHandler->invoke('scheduler', 'cron')\n#4 /var/www/drupal/web/core/lib/Drupal/Core/Cron.php(133): Drupal\\Core\\Cron->invokeCronHandlers()\n#5 /var/www/drupal/web/core/lib/Drupal/Core/ProxyClass/Cron.php(75): Drupal\\Core\\Cron->run()\n#6 /var/www/drupal/web/core/modules/automated_cron/src/EventSubscriber/AutomatedCron.php(65): Drupal\\Core\\ProxyClass\\Cron->run()\n#7 [internal function]: Drupal\\automated_cron\\EventSubscriber\\AutomatedCron->onTerminate(Object(Symfony\\Component\\HttpKernel\\Event\\PostResponseEvent), 'kernel.terminat...', Object(Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))\n#8 /var/www/drupal/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func(Array, Object(Symfony\\Component\\HttpKernel\\Event\\PostResponseEvent), 'kernel.terminat...', Object(Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher))\n#9 /var/www/drupal/vendor/symfony/http-kernel/HttpKernel.php(88): Drupal\\Component\\EventDispatcher\\ContainerAwareEventDispatcher->dispatch('kernel.terminat...', Object(Symfony\\Component\\HttpKernel\\Event\\PostResponseEvent))\n#10 /var/www/drupal/vendor/stack/builder/src/Stack/StackedHttpKernel.php(32): Symfony\\Component\\HttpKernel\\HttpKernel->terminate(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Drupal\\Core\\Cache\\CacheableJsonResponse))\n#11 /var/www/drupal/web/core/lib/Drupal/Core/DrupalKernel.php(643): Stack\\StackedHttpKernel->terminate(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Drupal\\Core\\Cache\\CacheableJsonResponse))\n#12 /var/www/drupal/web/index.php(22): Drupal\\Core\\DrupalKernel->terminate(Object(Symfony\\Component\\HttpFoundation\\Request), Object(Drupal\\Core\\Cache\\CacheableJsonResponse))\n#13 {main}

Ma seule action a été de virer une date de planif de news sur une news GAHE et visiblement tout est rentré ds l'ordre

**Comment by bmagic** [comment]
J'ai fixe j'ai utilisé un autre truc qui au final est plus propre!!
