### ISSUE TITLE
Plateformes jeu non personnalisables

### ISSUE THREAD

**Issue by mupfpilou** [Futurolan/ga-front#8]
Le champ plateforme des tournois est fixe, il faudrait que ca soit pas une liste texte fixe non modifiable.

A court terme, faudrait add un truc "Mobiles", et "Autres" pour se couvrir
mais le top, c que ca soit manageable ds le backend

**Comment by bmagic** [comment]
Si c'est totalement personnalisable par un administrateur sur cette page: 

https://backoffice.gamers-assembly.net/admin/structure/types/manage/tournament/fields/node.tournament.field_tournament_platform/storage


Donc bref quand t'as besoin d'une nouvelle plateforme tu créés un ticket et je rajoute, je pense pas que ce soit un truc qui se rajoute tous les jours :)
